name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1

      - uses: actions/setup-go@v6.2.0
        with:
          go-version-file: go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          version: v2.8.0

      - name: Run checks
        run: make ci

      - name: Build
        run: make build
